### ISSUE TITLE
Lack of file: test_logger.py

### ISSUE THREAD

**Issue by scb-vs5** [snakers4/mnasnet-pytorch#3]
Hi,when I try to excute the train.py ,it reports " ModuleNotFoundError: No module named 'utils.text_logger' ".So，whether you forgot to upload the text_logger.py in the directory 'utils'? or I miss something important?

**Comment by snakers4** [comment]
Forgot to upload this file
Just comment out this line
This is just logs

**Comment by scb-vs5** [comment]
ok, thank you! 
hope it finish better
